/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jshop.Forms;

import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 *
 * @author bartek
 */
public class ChooseActionPanel extends javax.swing.JPanel {

    private short chooseAction;
    /**
     * Creates new form CustomerChooseActionPanel
     */
    public ChooseActionPanel() throws InterruptedException {
        initComponents();        
        chooseAction = 0;
    }
    
    public short getChooseAction() {
        return chooseAction;
    }
    
    private void showParentWindow() {
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
           window.dispose();
        }
    }
    
    public void ButtonAddSetText(String text) {
        ButtonAddAction.setText(text);
    }
    
    public void ButtonShowSetText(String text) {
        ButtonShowAction.setText(text);
    }
        
    public void ButtonEditSetText(String text) {
        ButtonEditAction.setText(text);
    }
            
    public void ButtonRemoveSetText(String text) {
        ButtonRemoveAction.setText(text);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonEditAction = new javax.swing.JButton();
        ButtonRemoveAction = new javax.swing.JButton();
        ButtonAddAction = new javax.swing.JButton();
        ButtonShowAction = new javax.swing.JButton();

        ButtonEditAction.setText("Edytuj zamówienie");
        ButtonEditAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEditActionMouseClicked(evt);
            }
        });

        ButtonRemoveAction.setText("Usuń zamówienie");
        ButtonRemoveAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonRemoveActionMouseClicked(evt);
            }
        });

        ButtonAddAction.setText("Dodaj zamówienie");
        ButtonAddAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddActionMouseClicked(evt);
            }
        });

        ButtonShowAction.setText("Zobacz zamówienie");
        ButtonShowAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonShowActionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonRemoveAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonEditAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonShowAction, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(ButtonAddAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonAddAction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonShowAction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonEditAction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonRemoveAction)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void ButtonEditActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEditActionMouseClicked
        chooseAction = 3;
        showParentWindow();
    }//GEN-LAST:event_ButtonEditActionMouseClicked

    private void ButtonRemoveActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRemoveActionMouseClicked
        chooseAction = 4;
        showParentWindow();
    }//GEN-LAST:event_ButtonRemoveActionMouseClicked

    private void ButtonAddActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddActionMouseClicked
        chooseAction = 1;
        showParentWindow();
    }//GEN-LAST:event_ButtonAddActionMouseClicked

    private void ButtonShowActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonShowActionMouseClicked
        chooseAction = 2;
        showParentWindow();
    }//GEN-LAST:event_ButtonShowActionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddAction;
    private javax.swing.JButton ButtonEditAction;
    private javax.swing.JButton ButtonRemoveAction;
    private javax.swing.JButton ButtonShowAction;
    // End of variables declaration//GEN-END:variables
}
