/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jshop.Forms;

import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 *
 * @author bartek
 */
public class CustomerChooseActionPanel extends javax.swing.JPanel {

    private short chooseAction;
    /**
     * Creates new form CustomerChooseActionPanel
     */
    public CustomerChooseActionPanel() throws InterruptedException {
        initComponents();        
        chooseAction = 0;
    }
    
    public short getChooseAction() {
        return chooseAction;
    }
    
    private void showParentWindow() {
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
           window.dispose();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonCustomerEdit = new javax.swing.JButton();
        ButtonCustomerRemove = new javax.swing.JButton();
        ButtonCustomerAdd = new javax.swing.JButton();
        ButtonCustomerShow = new javax.swing.JButton();

        ButtonCustomerEdit.setText("Edytuj klienta");
        ButtonCustomerEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCustomerEditMouseClicked(evt);
            }
        });

        ButtonCustomerRemove.setText("Usuń klienta");
        ButtonCustomerRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCustomerRemoveMouseClicked(evt);
            }
        });

        ButtonCustomerAdd.setText("Dodaj klienta");
        ButtonCustomerAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCustomerAddMouseClicked(evt);
            }
        });

        ButtonCustomerShow.setText("Zobacz klienta");
        ButtonCustomerShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCustomerShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonCustomerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCustomerShow))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonCustomerEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCustomerRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCustomerAdd)
                    .addComponent(ButtonCustomerShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCustomerEdit)
                    .addComponent(ButtonCustomerRemove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void ButtonCustomerEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCustomerEditMouseClicked
        chooseAction = 3;
        showParentWindow();
    }//GEN-LAST:event_ButtonCustomerEditMouseClicked

    private void ButtonCustomerRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCustomerRemoveMouseClicked
        chooseAction = 4;
        showParentWindow();
    }//GEN-LAST:event_ButtonCustomerRemoveMouseClicked

    private void ButtonCustomerAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCustomerAddMouseClicked
        chooseAction = 1;
        showParentWindow();
    }//GEN-LAST:event_ButtonCustomerAddMouseClicked

    private void ButtonCustomerShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCustomerShowMouseClicked
        chooseAction = 2;
        showParentWindow();
    }//GEN-LAST:event_ButtonCustomerShowMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCustomerAdd;
    private javax.swing.JButton ButtonCustomerEdit;
    private javax.swing.JButton ButtonCustomerRemove;
    private javax.swing.JButton ButtonCustomerShow;
    // End of variables declaration//GEN-END:variables
}
