/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jshop.Forms;

import java.awt.Window;
import java.util.Date;
import javax.swing.SwingUtilities;

/**
 *
 * @author bartek
 */
public class CustomerAddPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAddPanel
     */
    public CustomerAddPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldName = new javax.swing.JTextField();
        LabelPeselNumber = new javax.swing.JLabel();
        TextFieldSurname = new javax.swing.JTextField();
        LabelGender = new javax.swing.JLabel();
        TextFieldPeselNumber = new javax.swing.JTextField();
        LabelDateOfBirth = new javax.swing.JLabel();
        RadioButtonWomen = new javax.swing.JRadioButton();
        LabelAddress = new javax.swing.JLabel();
        RadioButtonMen = new javax.swing.JRadioButton();
        LabelEmail = new javax.swing.JLabel();
        DateChooserBirthDay = new com.toedter.calendar.JDateChooser();
        LabelBalance = new javax.swing.JLabel();
        TextFieldAddress = new javax.swing.JTextField();
        ButtonAddCustomerDialog = new javax.swing.JButton();
        TextFieldEmail = new javax.swing.JTextField();
        SpinnerBalance = new javax.swing.JSpinner();
        LabalName = new javax.swing.JLabel();
        LabelSurname = new javax.swing.JLabel();

        TextFieldName.setText("jTextField1");

        LabelPeselNumber.setText("Numer PESEL");

        TextFieldSurname.setText("jTextField2");

        LabelGender.setText("Płeć");

        TextFieldPeselNumber.setText("jTextField3");

        LabelDateOfBirth.setText("Data urodzenia");

        RadioButtonWomen.setText("Kobieta");

        LabelAddress.setText("Adres");

        RadioButtonMen.setSelected(true);
        RadioButtonMen.setText("Mężczyzna");

        LabelEmail.setText("Email");

        LabelBalance.setText("Saldo");

        TextFieldAddress.setText("jTextField4");

        ButtonAddCustomerDialog.setText("Dodaj klienta");
        ButtonAddCustomerDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddCustomerDialogMouseClicked(evt);
            }
        });

        TextFieldEmail.setText("jTextField5");

        SpinnerBalance.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        SpinnerBalance.setName(""); // NOI18N

        LabalName.setText("Imię");

        LabelSurname.setText("Nazwisko");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelGender)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelDateOfBirth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ButtonAddCustomerDialog)
                                        .addGap(154, 154, 154))
                                    .addComponent(DateChooserBirthDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAddress)
                                    .addComponent(LabelEmail)
                                    .addComponent(LabelBalance))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(TextFieldAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SpinnerBalance)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabalName)
                                    .addComponent(LabelSurname)
                                    .addComponent(LabelPeselNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioButtonMen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                        .addComponent(RadioButtonWomen))
                                    .addComponent(TextFieldSurname)
                                    .addComponent(TextFieldPeselNumber)
                                    .addComponent(TextFieldName))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabalName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPeselNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPeselNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonWomen)
                    .addComponent(RadioButtonMen)
                    .addComponent(LabelGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateChooserBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDateOfBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonAddCustomerDialog)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Date getDateBirthDay() {
        Date date = DateChooserBirthDay.getDate();
        return date;
    }
    
    public String getName() {
        return TextFieldName.getText();
    }
    
    public String getSurname() {
        return TextFieldSurname.getText();
    }
    
    public String getPeselNumber() {
        return TextFieldPeselNumber.getText();
    }
    
    public String getEmail() {
        return TextFieldEmail.getText();
    }
    
    public String getAddress() {
        return TextFieldAddress.getText();
    }
    
    public boolean getGender() {
        //true - Men, false - Women
        return RadioButtonMen.isSelected();
    }
    
    public float getBalace() {
        
    }
    
    private void ButtonAddCustomerDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddCustomerDialogMouseClicked
        Window win = SwingUtilities.getWindowAncestor(this);
        if (win != null) {
           win.dispose();
        }
    }//GEN-LAST:event_ButtonAddCustomerDialogMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddCustomerDialog;
    private com.toedter.calendar.JDateChooser DateChooserBirthDay;
    private javax.swing.JLabel LabalName;
    private javax.swing.JLabel LabelAddress;
    private javax.swing.JLabel LabelBalance;
    private javax.swing.JLabel LabelDateOfBirth;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelGender;
    private javax.swing.JLabel LabelPeselNumber;
    private javax.swing.JLabel LabelSurname;
    private javax.swing.JRadioButton RadioButtonMen;
    private javax.swing.JRadioButton RadioButtonWomen;
    private javax.swing.JSpinner SpinnerBalance;
    private javax.swing.JTextField TextFieldAddress;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldPeselNumber;
    private javax.swing.JTextField TextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
