/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jshop.Forms;


/**
 *
 * @author bartek
 */
public class MainPanel extends javax.swing.JPanel {
//TODO:
/**
 * gdy usuwany klient lub produkt to sprawdzic powiazane zlecenia
 * import projektu do eclipse :v
 */
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        customerPanel1 = new jshop.Forms.Customer.CustomerPanel();
        productPanel1 = new jshop.Forms.Product.ProductPanel();
        orderPanel1 = new jshop.Forms.Order.OrderPanel();
        settingPanel1 = new jshop.Forms.Setting.SettingPanel();

        jTabbedPane1.addTab("Klienci", customerPanel1);
        jTabbedPane1.addTab("Produkty", productPanel1);
        jTabbedPane1.addTab("Zamówienia", orderPanel1);
        jTabbedPane1.addTab("Ustawienia", settingPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jshop.Forms.Customer.CustomerPanel customerPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private jshop.Forms.Order.OrderPanel orderPanel1;
    private jshop.Forms.Product.ProductPanel productPanel1;
    private jshop.Forms.Setting.SettingPanel settingPanel1;
    // End of variables declaration//GEN-END:variables
}
