/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jshop.Forms.Order;

import java.awt.AWTEvent;
import java.awt.Dialog;
import java.awt.Window;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractListModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SwingUtilities;
import jshop.Classes.Customer;
import jshop.Classes.Product;
import jshop.Enums.OrderType;
import jshop.Forms.Customer.CustomerPanel;
import jshop.Forms.InfoPanel;
import jshop.Forms.Product.ProductPanel;
import static jshop.Forms.Product.ProductPanel.getProductMap;

/**
 *
 * @author bartek
 */
public class OrderFormPanel extends javax.swing.JPanel {

    private DefaultComboBoxModel<String> customerComboBoxModel;
    private DefaultComboBoxModel<String> productComboBoxModel;
    private DefaultListModel<String> productListModel;
    private List<Product> productList;
    private Map<Integer, Product> productListBind;
    private InfoPanel infoPanel; 
    
    /**
     * Creates new form OrderFormPanel
     */
    public OrderFormPanel() {
        
        customerComboBoxModel = new DefaultComboBoxModel<>();
        productComboBoxModel = new DefaultComboBoxModel<>();
        productListModel = new DefaultListModel<>();
        productList = new ArrayList<Product>();
        productListBind = new HashMap<Integer, Product>();
        initComponents();              
    }
    
    public void setType(OrderType orderType) {
        ComboBoxType.setSelectedItem(orderType.toString());
    }
    
    public OrderType getType() {
        return OrderType.valueOf(ComboBoxType.getSelectedItem().toString());
    }
    
    public void setCustomer(Customer customer) {        
        if(CustomerPanel.getCustomerMap().get(customer.getId()) != null) {
            SpinnerClientId.setValue(customer.getId());
        }        
    }
    
    public Customer getCustomer() {
        Customer customer;
        if((customer = CustomerPanel.getCustomerMap().get((int)SpinnerClientId.getValue())) != null) {
            return customer;
        }
        else {
            return null;
        }
    }
    
    public void setProduct(List<Product> products) { 
        
        if(products != null) {
            for(int i = 0; i < products.size(); i++) {
                Product product = products.get(i);
                String productInfo = new String(
                    product.getName() + " [" +
                    product.getType() + "][Id: " +
                    product.getId() + "]"
                );
                productListModel.addElement(productInfo);
                productList.add(product);
            }
        }
        
       /* for(int i = 0; i <= getProductMap().size(); i++) {
                            Product tempProduct = getProduct(i);
                            if(tempProduct != null) {
                                String productInfo = product.getName() + " [" + product.getType() + "][" + product.getPrice() + "PLN] (id: " + product.getId() + ")";
                                listModel.addElement(productInfo);
                            }                            
                        }*/

    }
    
    public List<Product> getProduct() {
        return productList;
    }

    public void setButtonText(String text) {
        ButtonActionOrderDialog.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelType = new javax.swing.JLabel();
        ComboBoxType = new javax.swing.JComboBox<>();
        LabelCustomer = new javax.swing.JLabel();
        LabelProducts = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListProducts = new javax.swing.JList<>();
        ButtonActionOrderDialog = new javax.swing.JButton();
        SpinnerProductId = new javax.swing.JSpinner();
        ButtonProductAdd = new javax.swing.JButton();
        SpinnerClientId = new javax.swing.JSpinner();
        ButtonClientsShow = new javax.swing.JButton();
        ButtonProductsShow = new javax.swing.JButton();

        LabelType.setText("Typ");

        ComboBoxType.setModel(new DefaultComboBoxModel(OrderType.values()));

        LabelCustomer.setText("Klient");

        LabelProducts.setText("Produkty");

        ListProducts.setModel(productListModel);
        ListProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListProducts.setEnabled(false);
        jScrollPane1.setViewportView(ListProducts);

        ButtonActionOrderDialog.setText("Dodaj zamówienie");
        ButtonActionOrderDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonActionOrderDialogMouseClicked(evt);
            }
        });

        SpinnerProductId.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ButtonProductAdd.setText("Dodaj produkt");
        ButtonProductAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonProductAddMouseClicked(evt);
            }
        });

        SpinnerClientId.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ButtonClientsShow.setText("Pokaż klientów");
        ButtonClientsShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonClientsShowMouseClicked(evt);
            }
        });

        ButtonProductsShow.setText("Pokaż produkty");
        ButtonProductsShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonProductsShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelType)
                            .addComponent(LabelCustomer)
                            .addComponent(LabelProducts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SpinnerProductId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(SpinnerClientId, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonClientsShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonProductsShow, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonProductAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(ButtonActionOrderDialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelType)
                    .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCustomer)
                    .addComponent(SpinnerClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClientsShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProducts)
                    .addComponent(ButtonProductsShow))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(ButtonProductAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonActionOrderDialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionOrderDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonActionOrderDialogMouseClicked
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
           window.dispose();
        }
    }//GEN-LAST:event_ButtonActionOrderDialogMouseClicked

    private void ButtonClientsShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonClientsShowMouseClicked
        infoPanel = new InfoPanel();
        JDialog dialog = null;
        //show 
        if (dialog == null) {
            Window win = SwingUtilities.getWindowAncestor(this);
            if (win != null) {
                dialog = new JDialog(win, "Klienci",
                        Dialog.ModalityType.APPLICATION_MODAL);
                dialog.getContentPane().add(infoPanel);
                dialog.pack();
                dialog.setLocationRelativeTo(null);
            }
        }
        infoPanel.InfoPanelCustomer(CustomerPanel.getCustomerMap());
        dialog.setVisible(true); // here the modal dialog takes over        
    }//GEN-LAST:event_ButtonClientsShowMouseClicked

    private void ButtonProductsShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonProductsShowMouseClicked
        infoPanel = new InfoPanel();
        JDialog dialog = null;
        //show 
        if (dialog == null) {
            Window win = SwingUtilities.getWindowAncestor(this);
            if (win != null) {
                dialog = new JDialog(win, "Produkty",
                        Dialog.ModalityType.APPLICATION_MODAL);
                dialog.getContentPane().add(infoPanel);
                dialog.pack();
                dialog.setLocationRelativeTo(null);
            }
        }
        infoPanel.InfoPanelProduct(ProductPanel.getProductMap());
        dialog.setVisible(true); // here the modal dialog takes over        
    }//GEN-LAST:event_ButtonProductsShowMouseClicked

    private void ButtonProductAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonProductAddMouseClicked
        Product product;
        if((product = ProductPanel.getProductMap().get((int)SpinnerProductId.getValue())) != null) {
            String productInfo = new String(
                product.getName() + " [" +
                product.getType() + "][Id: " +
                product.getId() + "]"
            );
            productListModel.addElement(productInfo);
            productList.add(product);
        }
        else {
            showMessageDialog(null, "Nie ma takiego produktu!");
        }
    }//GEN-LAST:event_ButtonProductAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActionOrderDialog;
    private javax.swing.JButton ButtonClientsShow;
    private javax.swing.JButton ButtonProductAdd;
    private javax.swing.JButton ButtonProductsShow;
    private javax.swing.JComboBox<String> ComboBoxType;
    private javax.swing.JLabel LabelCustomer;
    private javax.swing.JLabel LabelProducts;
    private javax.swing.JLabel LabelType;
    private javax.swing.JList<String> ListProducts;
    private javax.swing.JSpinner SpinnerClientId;
    private javax.swing.JSpinner SpinnerProductId;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
