/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jshop.Forms.Customer;

import java.awt.Dialog;;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import jshop.Classes.Customer;
import jshop.Classes.ShopException;
import jshop.Forms.ChooseActionPanel;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author bartek
 */
public class CustomerPanel extends javax.swing.JPanel /*implements ListModel<Order>*/ {
    
    private CustomerFormPanel customerAddPanel;
    private ChooseActionPanel customerChooseActionPanel;    
    private int globalIdCounter;//Customers Id       
    private DefaultListModel<String> listModel;
    private static Map<Integer, Customer> customerMap;
     
    /**
    * Creates new form MainFramePanel
    */
    public CustomerPanel() {
        globalIdCounter = 0;
        customerMap = new HashMap<Integer, Customer>();
        listModel = new DefaultListModel<>();
        initComponents();     
        
    }
    
    /**
    * @return the customerMap
    */
    public static Map<Integer, Customer> getCustomerMap() {
        return customerMap;
    }
    
    //po kazdej zmiane odswiezac cala jliste z indeksami, zrobic powiazanie indeks list-obiekt
    private static void addCustomer(Customer cust) {
        getCustomerMap().put(cust.getId(), cust);
    }

    private static Customer getCustomer(int id) throws ShopException {
        if (getCustomerMap().get(id) == null) {
            return null;//or throw new MyException("Not found object with id: " + id);//what is better?
        } else {
            return getCustomerMap().get(id);//// TODO: 26.05.16 add safety search: if id doesn't exists return null or throws exception
        }
    }
    
    private static void removeCustomer(Customer customer) {
        getCustomerMap().remove(customer.getId());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListCustomers = new javax.swing.JList<>();
        ButtonCustomerAction = new javax.swing.JButton();
        SpinnerCustomerId = new javax.swing.JSpinner();
        LabelCustomerId = new javax.swing.JLabel();

        ListCustomers.setModel(listModel);
        ListCustomers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListCustomers);

        ButtonCustomerAction.setText("Wybierz akcję");
        ButtonCustomerAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCustomerActionMouseClicked(evt);
            }
        });

        SpinnerCustomerId.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        LabelCustomerId.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCustomerId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpinnerCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(ButtonCustomerAction, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCustomerId)
                    .addComponent(ButtonCustomerAction))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCustomerActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCustomerActionMouseClicked
        try {
            customerChooseActionPanel = new ChooseActionPanel();
            JDialog dialog = null;
            //show 
            if (dialog == null) {
                Window win = SwingUtilities.getWindowAncestor(this);
                if (win != null) {
                    dialog = new JDialog(win, "Wybierz akcję",
                            Dialog.ModalityType.APPLICATION_MODAL);
                    dialog.getContentPane().add(customerChooseActionPanel);
                    customerChooseActionPanel.ButtonAddSetText("Dodaj klienta");
                    customerChooseActionPanel.ButtonShowSetText("Zobacz klienta");
                    customerChooseActionPanel.ButtonEditSetText("Edytuj klienta");
                    customerChooseActionPanel.ButtonRemoveSetText("Usuń klienta");
                    dialog.pack();
                    dialog.setLocationRelativeTo(null);
                }
            }
            dialog.setVisible(true); // here the modal dialog takes over
            //get clicked button
            if(customerChooseActionPanel.getChooseAction() == 1) {//add                    
                dialog = null;
                customerAddPanel = new CustomerFormPanel();
                if (dialog == null) {            
                    Window win = SwingUtilities.getWindowAncestor(this);
                    if (win != null) {
                        dialog = new JDialog(win, "Dodaj klienta",
                                Dialog.ModalityType.APPLICATION_MODAL);
                        dialog.getContentPane().add(customerAddPanel);
                        dialog.pack();
                        dialog.setLocationRelativeTo(null);
                    }
                }
                dialog.setVisible(true); // here the modal dialog takes over
                //TODO check if datas from form is not null
                //get values from fields by getters      
                
                if(customerAddPanel.getName().equals("") ||
                    customerAddPanel.getSurname().equals("") ||
                    Long.toString(customerAddPanel.getPeselNumber()).length() != 11||
                    customerAddPanel.getDateBirthDay().equals("") ||
                    customerAddPanel.getAddress().equals("") ||
                    customerAddPanel.getEmail().equals("")) 
                {
                    throw new ShopException("Musisz wypełnić wszystkie pola!");                    
                }
                else {    
                    Date todayDate = new Date();  
                    //Pesel.CheckPesel(customerAddPanel.getPeselNumber());
                    //Pesel.CheckGender(customerAddPanel.getGender(), Long.toString(customerAddPanel.getPeselNumber()));
                    //Pesel.CheckDateOfBirth(customerAddPanel.getDateBirthDay(), Long.toString(customerAddPanel.getPeselNumber()));
                    Customer customer = new Customer(globalIdCounter,
                        customerAddPanel.getName(),
                        customerAddPanel.getSurname(),
                        customerAddPanel.getPeselNumber(),
                        customerAddPanel.getGender(),
                        customerAddPanel.getDateBirthDay(),
                        customerAddPanel.getAddress(),
                        customerAddPanel.getEmail(),
                        todayDate,
                        customerAddPanel.getBalance()
                    );
                    //add to collection
                    addCustomer(customer);
                    //listCustomerBind.put(customer.getId(), listItemsCounter);

                    //add to list
                    String customerInfo = customer.getName() + " " + customer.getSurname() + " (id: " + customer.getId() + ")";
                    listModel.addElement(customerInfo);
                    globalIdCounter++;
                }              
                
            }
            else if(customerChooseActionPanel.getChooseAction() == 2) {//show
                dialog = null;
                if(globalIdCounter != 0) {                            
                    //get id spinner from spinner
                    Customer cust = getCustomer((int) SpinnerCustomerId.getValue());
                    if(cust != null) {
                        String customerBirthDate = new SimpleDateFormat("yyyy-MM-dd").format(cust.getDateOfBirth());
                        String customerInfo = new String(           
                                "Id: " + cust.getId() + 
                                "\nImię: " + cust.getName() + 
                                "\nNazwisko: " + cust.getSurname() +
                                "\nPesel: " + cust.getPeselNumber() +
                                "\nPłeć: " + ((cust.getGender()) ? "Tak" : "Nie") +
                                "\nData urodzin: " + customerBirthDate +
                                "\nAdres: " + cust.getAddress() +
                                "\nAdres email: " + cust.getEmailAddress() +
                                "\nData rejestracji: " + cust.getSurname() +
                                "\nStan konta: " + cust.getBalance()
                    
                        );
                        showMessageDialog(this, customerInfo, "Informacje o kliencie", HEIGHT);
                    }
                    else {
                       throw new ShopException("Nie ma takiego klienta!"); 
                    }                    
                }
                else {
                    throw new ShopException("Brak klientów");
                }
                dialog = null;                    
            }
            else if(customerChooseActionPanel.getChooseAction() == 3 && globalIdCounter != 0) {//edit
                dialog = null;
                if(globalIdCounter != 0) {  
                    Customer cust = getCustomer((int) SpinnerCustomerId.getValue());
                    if(cust != null) {
                        customerAddPanel = new CustomerFormPanel();
                        if (dialog == null) {            
                            Window win = SwingUtilities.getWindowAncestor(this);
                            if (win != null) {
                                dialog = new JDialog(win, "Edytuj klienta",
                                        Dialog.ModalityType.APPLICATION_MODAL);
                                dialog.getContentPane().add(customerAddPanel);
                                customerAddPanel.setButtonText("Edytuj klienta");
                                dialog.pack();
                                dialog.setLocationRelativeTo(null);
                                
                                //set data
                                customerAddPanel.setName(cust.getName());
                                customerAddPanel.setSurname(cust.getSurname());
                                customerAddPanel.setPeselNumber(cust.getPeselNumber());
                                customerAddPanel.setGender(cust.getGender());
                                customerAddPanel.setDateBirthDay(cust.getDateOfBirth());
                                customerAddPanel.setAddress(cust.getAddress());
                                customerAddPanel.setEmail(cust.getEmailAddress());
                                customerAddPanel.setBalance(cust.getBalance());
                            }
                        }
                        dialog.setVisible(true); // here the modal dialog takes over
                        if(customerAddPanel.getName().equals("") ||
                            customerAddPanel.getSurname().equals("") ||
                            Long.toString(customerAddPanel.getPeselNumber()).length() != 11||
                            customerAddPanel.getDateBirthDay().equals("") ||
                            customerAddPanel.getAddress().equals("") ||
                            customerAddPanel.getEmail().equals("")) 
                        {
                            throw new ShopException("Musisz wypełnić wszystkie pola!");
                        }
                        else {
                            //save
                            cust.setName(customerAddPanel.getName());
                            cust.setSurname(customerAddPanel.getSurname());
                            cust.setPeselNumber(customerAddPanel.getPeselNumber());
                            cust.setGender(customerAddPanel.getGender());
                            cust.setDateOfBirth(customerAddPanel.getDateBirthDay());
                            cust.setAddress(customerAddPanel.getAddress());
                            cust.setEmailAddress(customerAddPanel.getEmail());
                            cust.setBalance(customerAddPanel.getBalance());

                            listModel.clear();
                            for(int i = 0; i <= getCustomerMap().size(); i++) {
                                Customer customer = getCustomer(i);
                                if(customer != null) {
                                    String customerInfo = customer.getName() + " " + customer.getSurname() + " (id: " + customer.getId() + ")";
                                    listModel.addElement(customerInfo);
                                }                            
                            } 
                        }
                    }
                    else {
                        throw new ShopException("Brak klientów");
                    }
                }
                else {
                    throw new ShopException("Brak klientów");
                }
                dialog = null; 
            }
            else if(customerChooseActionPanel.getChooseAction() == 4 && globalIdCounter != 0) {//remove
                dialog = null;
                if(globalIdCounter != 0) {  
                    Customer cust = getCustomer((int) SpinnerCustomerId.getValue());
                    if(cust != null) {
                        //remove from collection
                        removeCustomer(cust);
                        //reload list 
                        listModel.clear();
                        for(int i = 0; i <= getCustomerMap().size(); i++) {
                            Customer customer = getCustomer(i);
                            if(customer != null) {
                                String sb = customer.getName() + " " + customer.getSurname() + " (id: " + customer.getId() + ")";
                                listModel.addElement(sb);
                            }                            
                        } 
                    }
                    else {
                        throw new ShopException("Brak klientów");
                    }
                }
                else {
                    throw new ShopException("Brak klientów");
                }
                dialog = null; 
            }
        }
        catch (Exception ex) {
            showMessageDialog(null, ex.getMessage(), "Błąd ogólny programu",  JOptionPane.ERROR_MESSAGE);
        } 
        catch (ShopException ex) {
            showMessageDialog(null, ex.getMessage(), "Komunikat",  JOptionPane.ERROR_MESSAGE);
        }  

    }//GEN-LAST:event_ButtonCustomerActionMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCustomerAction;
    private javax.swing.JLabel LabelCustomerId;
    private javax.swing.JList<String> ListCustomers;
    private javax.swing.JSpinner SpinnerCustomerId;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
